### ISSUE TITLE
VS Intellisense not working with HeatWave

### ISSUE THREAD

**Issue by chrpai** [firegiant/HeatWaveSupport#1]
### HeatWave Version

0.9.0.5

### Visual Studio Version

17.3.5

### Repro Steps

Votive in v3 had intellisense in Visual Studio. Using VS 2022 17.4 and HeatWave 0.9.0.5 I'm not getting intellisene suggestions for documents with the http://wixtoolset.org/schemas/v4/wxs namespace.

### Actual Result

I didnt get any assistance from Visual Studio.

### Expected Result

I'd like to see element/attribute suggestions, descriptions and errors.

**Comment by chrpai** [comment]
I reinstalled VS and intellisense is working again.

**Comment by FireGiantHelp** [comment]
There seems to be many different ways to encounter this issue in Visual Studio, but we are pretty confident that HeatWave is not the cause of it. We're happy to hear reinstalling VS fixed the issue for you.
