### ISSUE TITLE
Manual migration and HeatWave migration from 3.x raises 'Duplicated Id' exception. 

### ISSUE THREAD

**Issue by flisak79** [firegiant/HeatWaveSupport#15]
### HeatWave Version

4.0.0-rc.1

### Visual Studio Version

17

### Repro Steps

1. Create custom UI dialog with two hide actions and different conditions
```
<Control Id="contorlId" Type="CheckBox" property="PROP1" CheckBoxValue="1">
       <Condition Action="hide">Condition A</Condition>
       <Condition Action="hide">Condition B</Condition>
       <Condition Action="show">Condition c</Condition>
</Control>
```
Manual migration and HeatWave migration from 3.x raises 'Duplicated Id' exception. After change:

```
<Control Id="contorlId" Type="CheckBox" property="PROP1" CheckBoxValue="1">
       <Condition Action="hide">Condition A OR B</Condition>
       <Condition Action="show">Condition c</Condition>
</Control>
```
 Migration works.

### Actual Result

'Duplicated Id' exception

### Expected Result

Migration without issues or information which file contains issues (in VS plugin)

**Comment by FireGiantHelp** [comment]
We identified that this is an issue in WiX v4 and have reported this issue there. We will integrate their fix as soon as they have it.
