### ISSUE TITLE
HeatWave Conversion skips reference

### ISSUE THREAD

**Issue by chrpai** [firegiant/HeatWaveSupport#2]
### HeatWave Version

0.9.0.5

### Visual Studio Version

17.3.5

### Repro Steps

I used HeatWave to convert a v3 wixproj to v4. It converted the IIS, NetFx and UI wixexts but not WiXVSExtension. It did update the vs namspace and vs:FindVisualSudio elements. Once the reference was fixed everything compiled and the custom action successfully ran during the install.

### Actual Result

The reference to the old extension was still present instead of the Nuget replacement.

### Expected Result

I expected to see WiXToolset.VisualStudio.wixext in the WiX Extensions dependencies.

**Comment by FireGiantHelp** [comment]
We can reproduce this internally. This issue is on our backlog to fix. We expect this to be fixed in the next preview release.

**Comment by FireGiantHelp** [comment]
This should be fixed in HeatWave v0.9.2. The `WiXVSExtension` should now be correctly converted to `WixToolset.VisualStudio.wixext`.
