### ISSUE TITLE
WixToolset.UI.wixext sporadically throws errors during build

### ISSUE THREAD

**Issue by EndOfCode** [firegiant/HeatWaveSupport#24]
### HeatWave Version

0.9.5

### Visual Studio Version

17.5.0

### Repro Steps

1. Create new empty MSI Setup Project
2. Added "WixToolset.UI.wixext" NuGet package
3. Added "`<UIRef Id="WixUI_InstallDir" />`" to "Package.wxs"
4. (Re-)build project

### Actual Result

Getting sporadically following error during build process of setup:

Severity	Code	Description	Project	File	Line	Suppression State
Error	WIX0204	ICE17: PushButton: 'Print' of Dialog: 'LicenseAgreementDlg' does not have an event defined in the ControlEvent table. It is a 'Do Nothing' button.	TestSetup	D:\a\wix4\wix4\src\ext\UI\wixlib\LicenseAgreementDlg.wxs	14

**Comment by FireGiantHelp** [comment]
WiX v4 introduced a new `ui:WixUI` element (from the UI extension) to reference the standard UIs. In WiX v4-rc.4 there should be an error message when trying to use `UIRef` element to directly reference standard UIs.
