### ISSUE TITLE
InstallDirDlg from WixToolset.UI.wixext package throws error during installation

### ISSUE THREAD

**Issue by EndOfCode** [firegiant/HeatWaveSupport#25]
### HeatWave Version

0.9.5

### Visual Studio Version

17.5.0

### Repro Steps

1. Create new empty MSI Setup Project
2. Added "WixToolset.UI.wixext" NuGet package
3. Added following to "Package.wxs"
`<UIRef Id="WixUI_InstallDir"`
`<UI>`
`   <Publish Dialog="WelcomeDlg" Control="Next" Event="NewDialog" Value="InstallDirDlg" Order="4"></Publish>`
`   <Publish Dialog="InstallDirDlg" Control="Back" Event="NewDialog" Value="WelcomeDlg" Order="4"></Publish>`
`</UI>`
5. (Re-)build project
6. Run msi Setup and go trough ui pages

### Actual Result

![2023-03-02 11_52_28-TestSetup](https://user-images.githubusercontent.com/99742641/222408408-222e7d83-82af-46cc-b671-ccc262df70ba.png)

**Comment by FireGiantHelp** [comment]
WiX v4 introduced a new `ui:WixUI` element (from the UI extension) to reference the standard UIs. In WiX v4-rc.4 there should be an error message when trying to use `UIRef` element to directly reference standard UIs.
