### ISSUE TITLE
Redistributing Heatwave / Silent Install

### ISSUE THREAD

**Issue by chrpai** [firegiant/HeatWaveSupport#28]
### HeatWave Version

0.9.0.5

### What's your idea?

I have a tool that has votive and/or heatwave as a prereq.  In the past I've instructed users to download and install them seperately.  I'd like to explore chaining them together using burn.  Would this be allowed for heatwave?  If so, would it be preferred to embed heatwave or do a download from web?  A stable URL for latest release would probably be a good thing.

**Comment by FireGiantHelp** [comment]
Redistributing HeatWave is fine. The VSIXs (2019 and 2022) are available on Visual Studio Marketplace. We do not control the URL format there so if you plan to download from web at install time, you may need to follow up with Visual Studio for their recommendations.
