### ISSUE TITLE
Project properties contain a broken "Resources" page

### ISSUE THREAD

**Issue by jmairboeck** [firegiant/HeatWaveSupport#32]
### HeatWave Version

1.0.1.1

### Visual Studio Version

17.5.4

### Repro Steps

1. Open project properties

### Actual Result

A nearly empty page named "Resources" (localized) is displayed as the last one after "Advanced". It only contains a link, offering to create a default resource file (Resources.resx). Clicking on that shows an error message.

It seems that this is inherited from a standard project type like C# because it is localized and non-functional.

### Expected Result

The extra properties page should be removed, like in the Wix Extension for Wix 3.

**Comment by FireGiantHelp** [comment]
This is a consequence of integration with the managed project systems in Visual Studio. Unfortunately, it is not currently possible to remove that property page. The Visual Studio team is aware of the issue.
