### ISSUE TITLE
Rust Custom Action Project Type

### ISSUE THREAD

**Issue by chrpai** [firegiant/HeatWaveSupport#4]
### HeatWave Version

0.9.0.5

### What's your idea?

Port wcautil and dutil to Rust and create a Rust custom action project template.

**Comment by FireGiantHelp** [comment]
We find Rust interesting but there is no Visual Studio support for Rust projects. Visual Studio support would be necessary before a custom action project templates in HeatWave would be useful.

**Comment by chrpai** [comment]
Maybe this is useful. https://github.com/PistonDevelopers/VisualRust
