### ISSUE TITLE
Computer restart required to see project templates in VS2022

### ISSUE THREAD

**Issue by mennodeij** [firegiant/HeatWaveSupport#45]
### HeatWave Version

1.0.2

### Visual Studio Version

17.5.3

### Repro Steps

1. Install Heatwave Extension from the Extensions menu
2. Close Visual Studio to start installation 
3. Finish installation with local admin priviliges
4. Restart Visual Studio
5. Select new project
6. No project templates listed under the WiX language
7. Restart computer
8. Start Visual Studio
9. Project templates are now listed under the WiX language

### Actual Result

I had to restart the computer to see the project templates

### Expected Result

I expected to have the WiX templates available upon restarting Visual Studio after the extension installation was complete

**Comment by chrpai** [comment]
It's been my experience that you sometimes have to start VS twice but reboot isn't needed.  You also have to make sure the project template filters are cleared and be patient with VS to update everything.  I don't think this is a WiX problem as I see it in my IsWiX also.  It's just a visual studio thing.

**Comment by firegiantco** [comment]
We are also unable to reproduce this and believe it to be a VS or VSIX installer issue and not related to HeatWave.
