### ISSUE TITLE
C# Custom Action Project does not work with .Net Framework 4.8.1

### ISSUE THREAD

**Issue by ghost** [firegiant/HeatWaveSupport#51]
### HeatWave Version

1.0.2.1

### Visual Studio Version

17.8.3

### Repro Steps

I tried to build a "C# Custom Action Project" with using .Net Framework 4.8.1. But the code wouldn't be invoked by the MSI. By using .Net 4.7.2, I was able to execute my code.

### Actual Result

I'm sorry, but I'm not motivated to assist you further more about this issue. If you are not motivated to handle it without my assistance, please just close this issue.

**Comment by FireGiantHelp** [comment]
We are not able to reproduce this issue. We started with the template and changed the `TargetFramework` property in the .csproj and the `supportedRuntime` in the `CustomAction.config` and found the custom action worked as expected on .NET Framework 4.8.1.
