### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by matlimatli** [firegiant/HeatWaveSupport#53]
### HeatWave Version

1.0.2

### Visual Studio Version

17.8.3

### Repro Steps

1. Run the vsix installer

### Actual Result

The installation fails according to the VSIX installer dialog. Also see attached log. 
[dd_VSIXInstaller_20231213135037_7ed4.log](https://github.com/firegiant/HeatWaveSupport/files/13661069/dd_VSIXInstaller_20231213135037_7ed4.log)

However, when running the install again, the installer says that the product is already installed. Unclear if it is fully installed, or in a half-installed state.

Moreover, I have similar problems on an offline system. The problem on the online system seems to be that the installer thinks that Windows 11 SDK is not installed (which it is), and then downloads an installer which has an unexpected hash. On the offline system, the installer also thinks that the SDK is not installed (which it is), and obviously fails to download it since there is no Internet connectivity.

### Expected Result

The installation succeeds

**Comment by matlimatli** [comment]
As a workaround, by first uninstalling the Windows SDK using the VS installer, it was possible to install HeatWave, both on the online and offline systems.

**Comment by firegiantco** [comment]
Unfortunately, the nature of the VSIX installer is that things get scheduled to be installed alongside our extension and we have no control over the process.  It's true the SDK installs can be particularly problematic.  But it's not something we have the ability to affect on our end.

Thanks for reporting this.
