### ISSUE TITLE
VS 2022 Heatwave Installer Project post build event variables such as $(ProjectDir) returns nothing

### ISSUE THREAD

**Issue by duncangroenewald** [firegiant/HeatWaveSupport#56]
### HeatWave Version

1.0.2

### Visual Studio Version

17.8.3

### Repro Steps

1. add the following line to the projects post build event 
   echo $(ProjectDir)
2. build the project

### Actual Result

Output is "echo off". 

### Expected Result

Expect to see the project directory

**Comment by FireGiantHelp** [comment]
Duplicate of #44
