### ISSUE TITLE
Wix is not binding the path for App.exe

### ISSUE THREAD

**Issue by Prakashwa** [firegiant/HeatWaveSupport#57]
### HeatWave Version

1..0.2

### Visual Studio Version

17.9.2

### Repro Steps

a.  Follow the tutorial  https://www.firegiant.com/docs/wix/tutorial/sprint2/replace-placeholder-component/
b. `<Component>
  <File Source="App.exe" />
</Component>`

### Actual Result

Error: Cannot find the File file 'App.exe'. The following paths were checked: App.exe	

### Expected Result

it should create msi package

**Comment by FireGiantHelp** [comment]
Make sure you follow the steps in the tutorial carefully. It is important to reference your App project from your WiX project.
