### ISSUE TITLE
VSIX installer fails

### ISSUE THREAD

**Issue by bomcilva** [firegiant/HeatWaveSupport#58]
### HeatWave Version

1.0.2

### Visual Studio Version

16.9.26

### Repro Steps

1. Run the VSIX installer
2. 

### Actual Result

Installer fails with exception "This extension is not installable on any currently installed products." Visual Studio 2019 is installed, .Net Framework 4.7.2 is installed. Please see attached installer log, What am I missing? 
[dd_VSIXInstaller_20240328120704_1250.log](https://github.com/firegiant/HeatWaveSupport/files/14795104/dd_VSIXInstaller_20240328120704_1250.log)
Any help would be appreciated.

**Comment by FireGiantHelp** [comment]
Unfortunately, Visual Studio 16.9 is out of service (since October 2022) and is not supported by HeatWave. Visual Studio 16.11 is the supported version of Visual Studio 2019 and HeatWave will install there.

**Comment by bomcilva** [comment]
Thank you very much! Very helpful indeed.
