### ISSUE TITLE
HeatWave 1.0.3 does not create new MSI projects on VS2022

### ISSUE THREAD

**Issue by H-Ashrafi** [firegiant/HeatWaveSupport#60]
### HeatWave Version

1.0.3

### Visual Studio Version

VS2022

### Repro Steps

1. Install Heatwave 1.0.3
2. Create a new Msi project in VS2022

### Actual Result

When creating a MSI project a message pop up 
"Attempting to access unavailable class" - the wording is not exact.
- Heatwave 1.0.2 does not have this issue.
- Although V 1.0.3 does not create the project, I can create .wxs files manually and the intelligence works fine. I do not have access to wix templates either, I simply create the files with .wxs extensions.

### Expected Result

A new MSI project in the Solution Explorer.

**Comment by FireGiantHelp** [comment]
Please provide the full version of Visual Studio you are using. Follow these instructions from the bug template:

> To find the Visual Studio Version, open Visual Studio, click the "Help" menu, choose "About Visual Studio" and look for "Current Version".

**Comment by H-Ashrafi** [comment]
Thanks.
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version **17.8.7**

**Comment by enny1170** [comment]
The Same Problem here, i'm unable to create a wix project.
Heatwave V1.03 installed today at Microsoft Visual Studio Enterprise 2022 (64-Bit) - Current
Version 17.8.7

after clicking create in the new package dialog a messagebox appers
![image](https://github.com/firegiant/HeatWaveSupport/assets/18047568/0248dad7-fb22-4ceb-aa57-ff3c516b8d25)
translated the Message means try to access a missing method.

Result is, i have to click on Cancel to leave the Dialo. Atfer that,the Folder for the Project are created. but is empty.

Expected the Project is created and added to the solution

**Comment by dcm99** [comment]
@H-Ashrafi and @enny1170 unfortunately you have to Update Visual Studio to 17.9 see #59

**Comment by FireGiantHelp** [comment]
FYI: We just released HeatWave v1.0.4, which supports the current Visual Studio version *and* Visual Studio's latest LTS. That means HeatWave should work with the latest VS 17.8 as well as the latest VS 17.9.

If the exception dialog is displayed, it is most likely a new issue, so please open a new issue and attach Visual Studio's ActivityLog.xml to provide enough context to differentiate issues.
