### ISSUE TITLE
Cannot install HeatWave (community edition) 1.0.4 on VS2022

### ISSUE THREAD

**Issue by MatthiasRInst** [firegiant/HeatWaveSupport#64]
### HeatWave Version

1.0.4

### Visual Studio Version

17.1.6

### Repro Steps

1. Download "HeatWave for VS2022" from Visual Studio Marketplace
2. Double-click the VSIX

I have both VS 2019 and 2022 installed, using 2022 for the WiX projects. Thus I downloaded only HeatWave for VS2022.

### Actual Result

HeatWave gets installed

### Expected Result

Error "This extension cannot be installed on the products currently installed"

Log file:
[dd_VSIXInstaller_20240516120720_0b00.log](https://github.com/firegiant/HeatWaveSupport/files/15333743/dd_VSIXInstaller_20240516120720_0b00.log)

**Comment by FireGiantHelp** [comment]
As the log shows, VS 17.8 or greater is required for VS2022.  You indicate you have only 17.1.6 installed.

**Comment by MatthiasRInst** [comment]
I do not see that VS version requirement neither at [https://www.firegiant.com/docs/heatwave/](https://www.firegiant.com/docs/heatwave/) nor at [https://marketplace.visualstudio.com/items?itemName=FireGiant.FireGiantHeatWaveDev17](https://marketplace.visualstudio.com/items?itemName=FireGiant.FireGiantHeatWaveDev17). Can you add that vital information, so that users know their prerequisites before trying to install that VSIX?
