### ISSUE TITLE
Include wix files are removed by conversion from Wix3.14 to Wix 4

### ISSUE THREAD

**Issue by RAppels2022** [firegiant/HeatWaveSupport#7]
### HeatWave Version

0.9.0.5

### Visual Studio Version

16.11.21

### Repro Steps

1. Wix project set up, folders for 'Fragments', 'Includes' and 'Resources'
2. The *.wxi files are in that 'Includes' folder
3. While converting from 3.14 to wix 4 in VS2019, all the include files have disappeared
4. The the errors come from those include files in the attached zip file.
5. The original project is restored from a backup.
 
![ProjectWindow](https://user-images.githubusercontent.com/99225034/202706043-872047a7-3919-409f-aef8-251c9537abc6.png)
[Actual Build output.txt](https://github.com/firegiant/HeatWaveSupport/files/10041252/Actual.Build.output.txt)
[Includes.zip](https://github.com/firegiant/HeatWaveSupport/files/10041299/Includes.zip)

### Actual Result

the conversion errors about the include files was unexpected.

### Expected Result

a working project in version WiX 4.x

**Comment by FireGiantHelp** [comment]
HeatWave should be converting `.wxi` files listed in your .wixproj. Can you provide the `WixSetupProject.wixproj` as well so we can investigate?

**Comment by RAppels2022** [comment]
Ok I can send you the project file.

 

For your information:

I have restored my project from backup as the conversion tool destroyed the wix project.

So this is the wix project that works and before the conversion.

 

Best Regards,

 

Ruud Appels

Amsterdam

The Netherlands

**Comment by FireGiantHelp** [comment]
This should be fixed in HeatWave v0.9.2. MSBuild items with the .wxi file extension should no longer be removed from the project.
