### ISSUE TITLE
Converted Wix Projects fail to build when outputs were named with `OutputName` instead of `TargetName`

### ISSUE THREAD

**Issue by BMurri** [firegiant/HeatWaveSupport#9]
### HeatWave Version

0.9.0.5

### Visual Studio Version

17.4.2

### Repro Steps

1. Create Wix v3 project ~ 4 or 5 years ago
2. Convert v3 project to v4

### Actual Result

Build fails because project cannot determine output directory

### Expected Result

Build succeeds.

Note: Replacing the property `OutputName` with `TargetName` fixes the issue.

**Comment by FireGiantHelp** [comment]
This issue is on our backlog to investigate.

**Comment by FireGiantHelp** [comment]
We are unable to reproduce this issue. Could you share your before-conversion `.wixproj` and/or after-conversion `msbuild.binlog` (msbuild -bl)? `OutputName` seems to still be supported in WiX v4.

If you do not want to share it here, you can send it to us privately at `support at firegiant.com`.

**Comment by FireGiantHelp** [comment]
We've tested a few scenarios but are unable to reproduce the issue. If you can provide the information requested above, we'll continue the investigation.
